/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Project {
  readonly id?: number;
  name: string;
  description?: string;
  countryCode: string;
  link?: string;
  tags?: Array<string>;
  startDate?: string;
  endDate?: string;
}
