/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { ProjectPagePageable } from './projectPagePageable';

export interface ProjectPage {
  content?: Array<Project>;
  pageable?: ProjectPagePageable;
  totalElements?: number;
  totalPages?: number;
}
